###
GET http://localhost:13000

###
GET http://localhost:13000/setup
###
POST http://localhost:13000/api/user/register
Content-Type: application/json

{
    "email": "email",
    "password": "password"
}

###

POST http://localhost:13000/api/user/login
Content-Type: application/json

{
    "email": "email",
    "password": "password"
}

###

POST http://localhost:13000/api/user/refresh
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJpZCI6MSwiZW1haWwiOiJlbWFpbCJ9LCJpYXQiOjE3NjI0NjA0MDMsImV4cCI6MTc2MjU0NjgwM30.f6JkoGxDgYTE40SZcgKwdSfKcLy0kC-3YTCYb-Xb5YE"
}

###

POST http://localhost:13000/api/user/logout
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJpZCI6MSwiZW1haWwiOiJlbWFpbCJ9LCJpYXQiOjE3NjI0NjAzNDksImV4cCI6MTc2MjU0Njc0OX0.Bhh3PItqB1K0nFomYzvmtkrcgDHnvAF7-jTnyH2nSEo"
}

###
GET http://localhost:13000/profile/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJpZCI6MSwiZW1haWwiOiJlbWFpbCJ9LCJpYXQiOjE3NjI0NTYyNDgsImV4cCI6MTc2MjQ1NjU0OH0.YULr6BOZt7u9Q4PJ-H6d17H_YsIQubG4jR8ahN-hv_k
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJpZCI6MiwiZW1haWwiOiJlbWFpbDIifSwiaWF0IjoxNzYyNDU2MzQ4LCJleHAiOjE3NjI0NTY2NDh9.L5dlDJKZ-0ROSYeaJ3TIjSOSNbG6Q2CClcburNbpN68

###
POST http://localhost:13000/profile/
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJpZCI6MSwiZW1haWwiOiJlbWFpbCJ9LCJpYXQiOjE3NjI0NTYyNDgsImV4cCI6MTc2MjQ1NjU0OH0.YULr6BOZt7u9Q4PJ-H6d17H_YsIQubG4jR8ahN-hv_k
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJpZCI6MiwiZW1haWwiOiJlbWFpbDIifSwiaWF0IjoxNzYyNDU2MzQ4LCJleHAiOjE3NjI0NTY2NDh9.L5dlDJKZ-0ROSYeaJ3TIjSOSNbG6Q2CClcburNbpN68
Content-Type: application/json

{
    "username": "username2",
    "description": "the coolest description"
}